sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/project koalaman/shellcheck /project/officeonline-install.sh

matrix:
  fast_finish: true
